- src/BaselineOfTheNoteTaker/BaselineOfTheNoteTaker.class.st
Hi hernan I fixed the reference to microEd.
> Fixing baseline

- src/TheNoteTaker-UI/NTSpApplication.class.st
- src/TheNoteTaker-UI/NTSpImportNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
Add the button on the interface of notes for to import notes
> add the button for import notes

- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteContentPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteTakerMainUI.class.st
- src/TheNoteTaker-UI/NTSpSearchCreatePresenter.class.st
Add the method NTMDEditorPresenter>>save: withExtension:
> Additional features

- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpAddNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpApplication.class.st
- src/TheNoteTaker-UI/NTSpImportFolderCommand.class.st
- src/TheNoteTaker-UI/NTSpImportNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpSearchCreatePresenter.class.st
- src/TheNoteTaker/NTSingleton.class.st
Address the issue reported by @Ducasse in #19.
> Renaming isValidNoteTitle: -> isValidNoteName:

- src/BaselineOfTheNoteTaker/BaselineOfTheNoteTaker.class.st
- src/TheNoteTaker-Tests/NTPersistencyTest.class.st
- src/TheNoteTaker-Tests/NTTestResource.class.st
- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI-Tests/package.st
- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTNoteObject.extension.st
- src/TheNoteTaker-UI/NTSpNoteContentPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteTakerMainUI.class.st
Adding tests for user interface of notes and fixing bugs.
> Adding tests & fixing bugs

- src/BaselineOfTheNoteTaker/BaselineOfTheNoteTaker.class.st
- Fix error in baseline: method specification
- Remove unneeded NeoJSON load
> Fix load error

- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteContentPresenter.class.st
Redefine the title of a note after saving it;
set the contents of a note after editing it
> The next of refactoring code in user interfaces

- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteContentPresenter.class.st
add the testAddContentThenNameNoteIsInISOFormat
> Tests of user interfaces

- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpImportNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpNoteContentPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
- src/TheNoteTaker/NTNoteObject.class.st
refactoring of tests code to use FileSystem; add the test testSelectANote
> The next of tests user interfaces

- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpRemoveNoteCommand.class.st
> remove the file note while removing the note object

- src/TheNoteTaker-Tests/NTPersistencyTest.class.st
- src/TheNoteTaker-Tests/NTTestResource.class.st
- src/TheNoteTaker-UI/NTMDEditorPresenter.class.st
- src/TheNoteTaker-UI/NTNoteObject.extension.st
- src/TheNoteTaker-UI/NTNullNoteObject.extension.st
- src/TheNoteTaker/NTNoteObject.class.st
- src/TheNoteTaker/NTNullNoteObject.class.st
- src/TheNoteTaker/NTTag.class.st
Remove unused #neoJsonMapping methods.
Move UI methods to the UI package.
Add simple tests
> Remove neoJSON dependency

- src/BaselineOfTheNoteTaker/BaselineOfTheNoteTaker.class.st
- src/TheNoteTaker/MDFile.extension.st
Load MicroEd from pillar-markup repository
Load Microdown Extensions group
> Load MicroEd from pillar-markup repository

- src/TheNoteTaker-Tests/NTNoteObjectTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpEditorFilePresenterTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI/NTEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpAddNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpAddTagCommand.class.st
- src/TheNoteTaker-UI/NTSpApplication.class.st
- src/TheNoteTaker-UI/NTSpEditorPresenter.class.st
- src/TheNoteTaker-UI/NTSpImportFolderCommand.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteTakerMainUI.class.st
- src/TheNoteTaker-UI/NTSpRemoveNoteCommand.class.st
- src/TheNoteTaker-UI/NTSpRemoveTagCommand.class.st
- src/TheNoteTaker-UI/NTSpSearchCreatePresenter.class.st
- src/TheNoteTaker/NTISOFileNamer.class.st
- src/TheNoteTaker/NTLog.class.st
- src/TheNoteTaker/NTNoteObject.class.st
- src/TheNoteTaker/NTSettings.class.st
- src/TheNoteTaker/NTSingleton.class.st
I have Fix many bugs.
I have also add Tags to note, we can now add and remove a tag to a note in the application
We can save and load a note with a Tag
> Fix and Tags

- src/TheNoteTaker-UI-Tests/NTSpNoteIndexPresenterTest.class.st
- src/TheNoteTaker-UI/NTNotePresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
- src/TheNoteTaker-UI/NTSpNoteTakerMainUI.class.st
> 57 impossible to navigate the notes

- src/TheNoteTaker-UI-Tests/NTSpEditorFilePresenterTest.class.st
- src/TheNoteTaker-UI/NTSpEditorPresenter.class.st
- src/TheNoteTaker/NTContainer.class.st
> fix: delete note bug and add a test for it

- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
> fix: remove allowTagCreation from tag filter

- src/TheNoteTaker-UI-Tests/NTSpNoteIndexPresenterTest.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
> feat: prevent to create empty note by submit empty search bar

- src/TheNoteTaker-UI-Tests/NTSpApplicationTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpCommandTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpEditorFilePresenterTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpNoteTakerMainUITest.class.st
- src/TheNoteTaker-UI-Tests/NTSpTagSelectionDialogTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpTestCase.class.st
- src/TheNoteTaker-UI/NTSpApplication.class.st
- src/TheNoteTaker-UI/NTSpNoteTakerMainUI.class.st
- src/TheNoteTaker-UI/NTSpOpenFolderCommand.class.st
- src/TheNoteTaker/NTContainer.class.st
I have change the open new folder logic, who Fixes #104 and Fixes #88 
Should Fixes #102 too
> Fix open folder by command and settings

- src/TheNoteTaker-Tests/NTContainerTest.class.st
- src/TheNoteTaker/NTContainer.class.st
> 63 add a test with more tags for   noteswith tags

- src/TheNoteTaker-UI-Tests/NTSpAddTagCommandTest.class.st
- src/TheNoteTaker-UI-Tests/NTSpRemoveTagCommandTest.class.st
- src/TheNoteTaker-UI/NTNotePresenter.class.st
- src/TheNoteTaker-UI/NTSpAddTagCommand.class.st
- src/TheNoteTaker-UI/NTSpNoteIndexPresenter.class.st
- src/TheNoteTaker-UI/NTSpRemoveTagCommand.class.st
> 130 adding and removing a tag deselect the note
